FROM node:18.16.0-alpine3.17
WORKDIR /app
COPY src/package*.json ./
COPY src/vite.config.js ./
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install --include=dev
COPY src .
EXPOSE 5173
CMD ["npm", "run", "dev"]
